typeset -U path
export EDITOR="nvim"
export BROWSER="firefox"
LS_COLORS=$LS_COLORS:'di=1;30:' ; export LS_COLORS
export PATH=$PATH:/bin:/usr/bin:/usr/sbin:/usr/local/bin:/opt:$HOME/.bin:$HOME/.nimble/bin
