autoload -U +X promptinit && promptinit
autoload -U +X compinit && compinit

# Autocompletion
zstyle ':completion:*' menu select
zstyle ':completion:*' use-cache true
zstyle ':completion:*' rehash true
setopt COMPLETE_ALIASES

## Options ##
compinit
promptinit
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt CORRECTALL
setopt AUTOCD
setopt NO_BEEP

unset GIT_ASKPASS
unset SSH_ASKPASS

#if [ "$TERM" = "xterm" ]; then
#    export TERM=xterm-256color
#fi

# Display a custom prompt
PROMPT="%(?.%F{green}.%F{red}) %~ ❯%f  %f"


# Colors input with use dircolors
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# if [ -f "/etc/dircolors" ]
# then
#   eval $(dircolors -b /etc/dircolors)
#   if [ -f "$HOME/.dircolors" ]
#   then
#     eval $(dircolors -b $HOME/.dircolors)
#   fi
# fi

# alias
alias ls='ls -F --color=auto --group-directories-first'
alias mp='ncmpcpp'
alias fm='spacefm'
alias grep='grep --color=auto'
alias vim='nvim'
alias vimrc='nvim ~/.config/nvim/init.vim'
# alias killall='pkill -x'

# History
export HISTSIZE=3000
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=$HISTSIZE
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

## Shortcuts ##
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^B" backward-char
bindkey "^F" forward-char
bindkey "^D" delete-char-or-list
bindkey '^H' backward-delete-char
bindkey '^W' backward-kill-word
bindkey '^L' clear-screen
bindkey '^V' quoted-insert
bindkey "^T" transpose-chars
bindkey "^U" kill-line
bindkey "^J" backward-word
bindkey "^K" forward-word
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward

# completion
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
# bindkey "^p" up-line-or-beginning-search # Up
# bindkey "^n" down-line-or-beginning-search # Down

bindkey "^p" history-beginning-search-backward
bindkey "^n" history-beginning-search-forward

# Delete key
bindkey "\e[3~" delete-char

# Edit command
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# # Search backwards and forwards with a pattern
# bindkey -M vicmd '/' history-incremental-pattern-search-backward
# bindkey -M vicmd '?' history-incremental-pattern-search-forward

# # set up for insert mode too
# bindkey -M viins '^p' history-incremental-pattern-search-backward
# bindkey -M viins '^n' history-incremental-pattern-search-forward


# Enable FZF

# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,.cargo,.cache,.icons,.wine,.mix,.ghc,.ocp,.npm,.dbus,.local,.mozilla,.steam}/*" 2> /dev/null'

# opam configuration
test -r /home/ogden/.opam/opam-init/init.zsh && . /home/ogden/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
# OPAM configuration
# . /home/ogden/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
# eval `opam config env`

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="/home/ogden/.sdkman"
# [[ -s "/home/ogden/.sdkman/bin/sdkman-init.sh" ]] && source "/home/ogden/.sdkman/bin/sdkman-init.sh"

# Load Rakubrew
eval "$(/home/ogden/.rakubrew/bin/rakubrew init Zsh)"

# Emacs vterm
vterm_printf(){
    if [ -n "$TMUX" ]; then
        # Tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

function mypass {
    ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -20
    pass "$@" 
    sleep 45
    greenclip print ' '
    ps axf | grep 'greenclip daemon' | grep -v grep | awk '{print $1}' | xargs kill -18
}
