#! /bin/sh
~/.config/bspwm/autostart.sh &
sxhkd &

bspc config border_width        3
bspc config window_gap         4

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
# bspc config focus_follows_pointer true
# bspc config ignore_ewmh_focus true
bspc config initial_polarity second_child

bspc monitor -d I II III IV V VI VII VIII IX X

# Colors
bspc config normal_border_color '#383838'
# bspc config focused_border_color '#DD704F' #orange
# bspc config focused_border_color '#704fdd'
bspc config focused_border_color '#4fbcdd'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
