export ZDOTDIR="~/.config/zsh"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export NO_AT_BRIDGE=1
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=gasp"
#export XDG_CURRENT_DESKTOP=sway
#export GTK_USE_PORTAL=1
#export XDG_CURRENT_DESKTOP=KDE

# Firefox Wayland support
if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    export MOZ_ENABLE_WAYLAND=1
fi
