# Ensure locale settings are properly set-up.
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Keep only the first occurence in path, cdpath etc.
# typeset -gU path
typeset -gU cdpath fpath mailpath path

export EDITOR="nvim"
export BROWSER="firefox-bin"
LS_COLORS=$LS_COLORS:'di=1;30:' ; export LS_COLORS
#export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/bin:/usr/sbin:/usr/local/bin:/opt:/usr/bin:/usr/sbin:/usr/local/bin:/opt:$HOME/.bin:$HOME/.nimble/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/dev/go/bin:/usr/lib/llvm/9/bin:/usr/lib/llvm/10/bin:/usr/lib/llvm/11/bin:$HOME/.luarocks/bin

export GOPATH=$HOME/dev/go

path+=("$HOME/.bin" "$HOME/.nimble/bin" "$HOME/.cargo/bin" "$HOME/dev/go/bin" "$HOME/.local/bin")
export PATH

# Home clean up
export XDG_STATE_HOME="$HOME/.local/state"
export ZDOTDIR="$HOME"/.config/zsh

export NIMBLE_DIR="$XDG_DATA_HOME/nimble"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export SDKMAN_DIR="$XDG_DATA_HOME"/sdkman

export ANDROID_HOME="$XDG_DATA_HOME"/android
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export PYTHONSTARTUP="/etc/python/pythonrc"

export CIN_CONFIG="$XDG_CONFIG_HOME"/bcast5
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export RXVT_SOCKET="$XDG_RUNTIME_DIR"/urxvtd
# export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export XCURSOR_PATH=/usr/share/icons:${XDG_DATA_HOME}/icons

export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass

# MAYBE
#export GNUPGHOME="$XDG_DATA_HOME"/gnupg
