# Download Znap, if it's not there yet.
[[ -f ~/.zsh/zsh-snap/znap.zsh ]] ||
    git clone https://github.com/marlonrichert/zsh-snap.git ~/.zsh/zsh-snap

# Znap setup
zstyle ':znap:*' repos-dir ~/.zsh/plugins
source ~/.zsh/zsh-snap/znap.zsh

# Disable default system prompt
# prompt off

zmodload zsh/complist
zmodload zsh/zle
autoload -Uz add-zsh-hook
autoload -Uz colors && colors

autoload -U +X promptinit && promptinit

# Autocompletion
unsetopt menu_complete      # do not autoselect the first completion entry
unsetopt flowcontrol        # disable start/stop flow control (^S/^Q)

setopt auto_menu            # show completion menu on successive tab press
setopt complete_in_word     # allow completion from within a word
setopt always_to_end        # move cursor to the end of the word on completion
setopt interactive_comments # allow comments
setopt auto_pushd           # make cd push the old dir onto the stack
setopt pushd_ignore_dups    # don't push multiple copies of the same dir
setopt pushdminus           # exchange the meaning of +/- when used with a number to specify a dir in the stack
setopt prompt_subst         # enable parameter expansion

# zstyle ':completion:*' menu select
# zstyle ':completion:*' use-cache true
# zstyle ':completion:*' rehash true
# setopt COMPLETE_ALIASES

# Keep home directory clean
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME"/zsh/zcompcache
compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION"
export HISTFILE="$XDG_STATE_HOME"/zsh/history

zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors
zstyle ':completion:*' use-cache yes
# zstyle ':completion:*' cache-path "$ZSH/cache"
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'

autoload -U +X compinit && compinit
# Enable Bash tab-completion
autoload -U +X bashcompinit && bashcompinit

## Options ##
compinit
promptinit
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt CORRECTALL
setopt AUTOCD
setopt NO_BEEP


unset GIT_ASKPASS
unset SSH_ASKPASS

#if [ "$TERM" = "xterm" ]; then
#    export TERM=xterm-256color
#fi

# Display a custom prompt
# PROMPT="%(?.%F{green}.%F{red}) %~ ❯%f  %f"

# `znap prompt` makes your prompt visible in less than 12ms!
znap prompt sindresorhus/pure
# znap prompt jackharrisonsherlock/common

# `znap source` automatically downloads and activates your plugins.
znap source  jocelynmallon/zshmarks

# Aliases for zshmarks
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"
alias l="showmarks"

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"


# Colors input with use dircolors
# if [ -x dircolors ]; then
   test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
# fi

# if [ -f "/etc/dircolors" ]
# then
#   eval $(dircolors -b /etc/dircolors)
#   if [ -f "$HOME/.dircolors" ]
#   then
#     eval $(dircolors -b $HOME/.dircolors)
#   fi
# fi

# alias
alias ls='ls -F --color=auto --group-directories-first'
alias diff='diff --color'
alias mp='ncmpcpp'
alias fm='spacefm'
alias grep='grep --color=auto'
alias vim='nvim'

alias vimrc='nvim ~/.config/nvim/init.lua'
alias zshrc='nvim ~/.config/zsh/.zshrc'
# alias killall='pkill -x'

# History
export HISTSIZE=3000
export SAVEHIST=$HISTSIZE
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

## Shortcuts ##
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^B" backward-char
bindkey "^F" forward-char
bindkey "^D" delete-char-or-list
bindkey '^H' backward-delete-char
bindkey '^W' backward-kill-word
bindkey '^L' clear-screen
bindkey '^V' quoted-insert
bindkey "^T" transpose-chars
bindkey "^U" kill-line
bindkey "^J" backward-word
bindkey "^K" forward-word
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward

# completion
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
# bindkey "^p" up-line-or-beginning-search # Up
# bindkey "^n" down-line-or-beginning-search # Down

bindkey "^p" history-beginning-search-backward
bindkey "^n" history-beginning-search-forward

# Delete key
bindkey "\e[3~" delete-char

# Edit command
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# # Search backwards and forwards with a pattern
# bindkey -M vicmd '/' history-incremental-pattern-search-backward
# bindkey -M vicmd '?' history-incremental-pattern-search-forward

# # set up for insert mode too
# bindkey -M viins '^p' history-incremental-pattern-search-backward
# bindkey -M viins '^n' history-incremental-pattern-search-forward

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/ogden/.sdkman"
[[ -s "/home/ogden/.sdkman/bin/sdkman-init.sh" ]] && source "/home/ogden/.sdkman/bin/sdkman-init.sh"

# Load Rakubrew
eval "$(/home/ogden/.rakubrew/bin/rakubrew init Zsh)"

