# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  # boot.extraModulePackages = with config.boot.kernelPackages; [ zenergy cpupower r8168 ];
  # Asus B550 TUF Gaming
  boot.extraModulePackages = with config.boot.kernelPackages; [ zenergy cpupower r8125];
  boot.loader.systemd-boot.enable = true;

  boot.blacklistedKernelModules = [ "r8169" ];

  boot.kernel.sysctl = {
    # Update kernel buffer to 64M
    #"net.core.wmem_max" = 67108864;
    # "net.core.rmem_max" = 67108864;
    "net.core.rmem_max" = 134217728;
    "net.core.wmem_max" = 134217728;
    "vm.dirty_bytes" = 268435456;
    "vm.dirty_background_bytes" = 134217728;

    # Set TCP buffer limit to 32M
    "net.ipv4.tcp_wmem" = "10240 87380 33554432";
    "net.ipv4.tcp_rmem" = "10240 87380 33554432";

    "net.ipv4.tcp_congestion_control" = "bbr";
    "net.core.default_qdisc" = "fq";
  };

  # Disable IPv6
  # networking.enableIPv6 = false;
  # "pcie_aspm=off"

  boot.kernelParams = [ 
    "initcall_blacklist=acpi_cpufreq_init"
    "amd_pstate=active"
    "amd_pstate.shared_mem=1"

    # Required to make OpenCL (and Davinci Resolve) work
    # https://github.com/NixOS/nixpkgs/issues/325378#issuecomment-2212732797
    # https://github.com/NixOS/nixpkgs/issues/324252#issuecomment-2205385051
    "nvidia.NVreg_EnableGpuFirmware=0"
    "nvidia.NVreg_RestrictProfilingToAdminUsers=0"
    "ipv6.disable=1"
  ];

  boot.kernel.sysctl."net.ipv6.conf.all.disable_ipv6" = true;

  # boot.kernelParams = ["ipv6.disable=1" "nvidia_drm.modeset=1"];

  # Enable periodic trim
  # TODO: okay, when it will run? On stratup/shutdown? Or during working system? D:
  # services.fstrim.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42f57787-0dd3-42ad-a837-889148d44d22";
      fsType = "ext4";
    };

  # old-home
  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/94bdb842-147b-4ad3-8687-ab7fd1143eff";
  #     fsType = "ext4";
  #   };


  # Samsung 500 GB
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e5183b41-fe36-46e8-9ca9-791fc20660d1";
      fsType = "ext4";
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A41E-E03C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/92c82f05-b5be-4c18-bf70-4484fbc1b003"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
