#!/bin/bash

Check(){
    # wget -q --spider http://google.com
    # [[ $? -eq 0 ]] && echo 1 || echo 0
    ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo 1 || echo 0
}

Weather(){
    wget -qO- https://p.ya.ru/$1 |\
        html-to-text | head -1 |\
        tr '\n' ' ' | sed -e 's/[^0-9+-]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /\n/g' |\
        head -2 > /tmp/my-temp
    local str1=$(cat /tmp/my-temp | sed -n 1p)
    local str2=$(cat /tmp/my-temp | sed -n 2p)

    echo "$str1 ˚C"
    # echo "$str2" # wind speed
}

if [ "$(Check)" == 1 ]; then
    Weather zaporizhia
else
    echo "Loading..."
fi
